# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-24 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('django_geoip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPlaceholderModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='geoplaceholder_geoplaceholdermodel', serialize=False, to='cms.CMSPlugin')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geoip.City', verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geoip.Country', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geoip.Region', verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
